import { AuditRun, Vulnerability } from "./types";

export const mockVulnerabilities: Vulnerability[] = [
  {
    file_path: "app.py",
    line_range: "23-27",
    vuln_type: "sql_injection",
    severity: "critical",
    description: "User input directly concatenated into SQL query without parameterization",
    source_code: 'query = f"SELECT * FROM users WHERE id = {user_id}"',
  },
  {
    file_path: "app.py",
    line_range: "34-36",
    vuln_type: "command_injection",
    severity: "critical",
    description: "Unsanitized user input passed directly to os.system()",
    source_code: 'os.system(f"ping {hostname}")',
  },
  {
    file_path: "app.py",
    line_range: "42-45",
    vuln_type: "path_traversal",
    severity: "high",
    description: "File path constructed from user input without validation",
    source_code: 'open(f"/data/{filename}", "r")',
  },
  {
    file_path: "app.py",
    line_range: "51-53",
    vuln_type: "unsafe_deserialization",
    severity: "high",
    description: "yaml.load() used without SafeLoader on untrusted input",
    source_code: "data = yaml.load(user_input)",
  },
];

export const mockAuditRun: AuditRun = {
  id: "audit-001",
  repo_name: "acme-corp/web-api",
  status: "completed",
  vulnerabilities: mockVulnerabilities,
  current_vuln_index: 4,
  patch_attempts: 0,
  max_retries: 3,
  pr_urls: [
    "https://github.com/acme-corp/web-api/pull/42",
    "https://github.com/acme-corp/web-api/pull/43",
    "https://github.com/acme-corp/web-api/pull/44",
    "https://github.com/acme-corp/web-api/pull/45",
  ],
  event_log: [
    "[CloneRepo] Cloned acme-corp/web-api, found 12 Python files",
    "[Auditor] Found 4 vulnerabilities in 12 files",
    "[SelectVuln] Processing vuln 1/4: sql_injection in app.py",
    "[Exploit] Generated pytest exploit for sql_injection",
    "[ExploitSandbox] exit_code=1, status=completed",
    "[Patcher] Generated fix for sql_injection in app.py (Attempt 1)",
    "[VerifySandbox] exit_code=0, status=completed, attempt=1",
    "[PRCreator] Opened PR: https://github.com/acme-corp/web-api/pull/42",
    "[SelectVuln] Processing vuln 2/4: command_injection in app.py",
    "[Exploit] Generated pytest exploit for command_injection",
    "[ExploitSandbox] exit_code=1, status=completed",
    "[Patcher] Generated fix for command_injection in app.py (Attempt 1)",
    "[VerifySandbox] exit_code=0, status=completed, attempt=1",
    "[PRCreator] Opened PR: https://github.com/acme-corp/web-api/pull/43",
    "[SelectVuln] Processing vuln 3/4: path_traversal in app.py",
    "[Exploit] Generated pytest exploit for path_traversal",
    "[ExploitSandbox] exit_code=1, status=completed",
    "[Patcher] Generated fix for path_traversal in app.py (Attempt 1)",
    "[VerifySandbox] exit_code=1, status=completed, attempt=1",
    "[Patcher] Generated fix for path_traversal in app.py (Attempt 2)",
    "[VerifySandbox] exit_code=0, status=completed, attempt=2",
    "[PRCreator] Opened PR: https://github.com/acme-corp/web-api/pull/44",
    "[SelectVuln] Processing vuln 4/4: unsafe_deserialization in app.py",
    "[Exploit] Generated pytest exploit for unsafe_deserialization",
    "[ExploitSandbox] exit_code=1, status=completed",
    "[Patcher] Generated fix for unsafe_deserialization in app.py (Attempt 1)",
    "[VerifySandbox] exit_code=0, status=completed, attempt=1",
    "[PRCreator] Opened PR: https://github.com/acme-corp/web-api/pull/45",
  ],
  started_at: "2025-07-25T10:30:00Z",
  completed_at: "2025-07-25T10:34:22Z",
};
