"""PR Creator Agent — creates GitHub PRs for verified patches."""
import logging
from ..state import AuditorState
from ..github_service import GitHubService
from ..config import get_settings

logger = logging.getLogger(__name__)


def pr_creator_node(state: AuditorState) -> dict:
    """LangGraph node that creates a GitHub PR for the patch and exploit test."""
    logger.info("PR Creator agent starting...")

    current_vuln = state.get("current_vuln")
    if not current_vuln:
        return {"event_log": ["[PRCreator] No vulnerability to create PR for."]}

    vuln_type = current_vuln.get("vuln_type", "vuln")
    desc = current_vuln.get("description", "Security fix")
    file_path = current_vuln.get("file_path", "unknown_file.py")
    lines = current_vuln.get("line_range", "unknown")
    severity = current_vuln.get("severity", "unknown")

    patch_code = state.get("patch_code", "")
    exploit_test_code = state.get("exploit_test_code", "")
    repo_name = state.get("repo_name", "")

    # Generate branch name
    branch_name = f"fix/{vuln_type}-{str(abs(hash(desc)))[:8]}"

    settings = get_settings()
    gh = GitHubService(token=settings.github_token)

    try:
        # Try to create feature branch — if 404, we likely don't have write access
        # In that case, fork the repo first
        try:
            gh.create_branch(repo_name, branch_name)
        except Exception as branch_err:
            if "404" in str(branch_err):
                # Fork the repo and create PR on our fork
                logger.info(f"No write access to {repo_name}, forking...")
                fork = gh.client.get_user().create_fork(gh.client.get_repo(repo_name))
                import time
                time.sleep(3)  # Wait for fork to be ready
                repo_name = fork.full_name
                gh.create_branch(repo_name, branch_name)
            else:
                raise

        # Commit patched file and exploit test atomically
        test_file_path = f"tests/test_{vuln_type}_exploit.py"
        files_to_commit = {
            file_path: patch_code,
            test_file_path: exploit_test_code,
        }
        gh.commit_files(
            repo_name,
            branch_name,
            files_to_commit,
            f"fix: patch {vuln_type} in {file_path}"
        )

        # Open Pull Request
        pr_title = f"🛡️ Security Fix: {vuln_type.replace('_', ' ').title()} in {file_path}"
        pr_body = (
            f"## Vulnerability Summary\n{desc}\n\n"
            f"**Severity:** `{severity}`\n"
            f"**File & Lines:** `{file_path}` (lines {lines})\n\n"
            f"## Reproduction Test\n"
            f"A pytest unit test (`{test_file_path}`) demonstrating the vulnerability has been added.\n\n"
            f"## Patch Description\n"
            f"Applied a fix to mitigate the `{vuln_type}` vulnerability.\n\n"
            f"---\n*This PR was automatically generated by the Autonomous Code Auditor.*"
        )

        pr = gh.open_pr(repo_name, branch_name, "main", pr_title, pr_body)
        pr_url = pr.html_url

        logger.info(f"PR created successfully: {pr_url}")

        return {
            "pr_urls": [pr_url],
            "event_log": [f"[PRCreator] Opened PR: {pr_url}"],
        }
    except Exception as e:
        logger.error(f"Failed to create PR: {e}")
        return {
            "event_log": [f"[PRCreator] Error creating PR: {str(e)}"],
        }

